# Addon provider
{{- range $name, $addon := $.Values.addon }}
  {{- $addonNamespace := default ( printf "%s-%s" $name "addon-system" ) (get $addon "namespace") }}
  {{- $addonName := $name }}
  {{- $addonVersion := get $addon "version" }}
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "1"
    "argocd.argoproj.io/sync-wave": "1"
  name: {{ $addonNamespace }}
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: AddonProvider
metadata:
  name: {{ $addonName }}
  namespace: {{ $addonNamespace }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "2"
    "argocd.argoproj.io/sync-wave": "2"
{{- if or $addonVersion $.Values.secretName }}
spec:
{{- end}}
{{- if $addonVersion }}
  version: {{ $addonVersion }}
{{- end }}
{{- if $.Values.secretName }}
  secretName: {{ $.Values.secretName }}
{{- end }}
{{- if $.Values.secretNamespace }}
  secretNamespace: {{ $.Values.secretNamespace }}
{{- end }}
{{- end }} {{/* range $name, $addon := .Values.addon */}}
